INSERT INTO nacionalidades (descripcion) VALUES
('Argentina'),
('Uruguaya'),
('Chilena'),
('Paraguaya'),
('Boliviana'),
('Brasileña'),
('Peruana'),
('Colombiana'),
('Venezolana');

INSERT INTO tipo_usuario (descripcion) VALUES
('Administrador'),
('Cliente');

INSERT INTO provincias (nombre) VALUES
('Buenos Aires'),
('Catamarca'),
('Chaco'),
('Chubut'),
('Córdoba'),
('Corrientes'),
('Entre Ríos'),
('Formosa'),
('Jujuy'),
('La Pampa'),
('La Rioja'),
('Mendoza'),
('Misiones'),
('Neuquén'),
('Río Negro'),
('Salta'),
('San Juan'),
('San Luis'),
('Santa Cruz'),
('Santa Fe'),
('Santiago del Estero'),
('Tierra del Fuego'),
('Tucumán'),
('Ciudad Autónoma de Buenos Aires');

INSERT INTO localidades (nombre, id_provincia) VALUES
('La Plata', 1),
('Mar del Plata', 1),
('Bahía Blanca', 1),
('Tigre', 1),
('Quilmes', 1),
('Avellaneda', 1),
('San Justo', 1),
('Lomas de Zamora', 1),
('Morón', 1),
('San Nicolás', 1),
('San Fernando del Valle', 2),
('Tinogasta', 2),
('Belén', 2),
('Andalgalá', 2),
('Santa María', 2),
('Recreo', 2),
('Pomán', 2),
('Fiambalá', 2),
('La Puerta', 2),
('Mutquín', 2),
('Resistencia', 3),
('Sáenz Peña', 3),
('Villa Ángela', 3),
('Charata', 3),
('General San Martín', 3),
('Machagai', 3),
('Las Breñas', 3),
('Quitilipi', 3),
('Castelli', 3),
('Fontana', 3),
('Rawson', 4),
('Comodoro Rivadavia', 4),
('Trelew', 4),
('Puerto Madryn', 4),
('Esquel', 4),
('Gaiman', 4),
('Dolavon', 4),
('Rada Tilly', 4),
('Sarmiento', 4),
('Paso de Indios', 4),
('Córdoba', 5),
('Villa María', 5),
('Río Cuarto', 5),
('San Francisco', 5),
('Alta Gracia', 5),
('Villa Carlos Paz', 5),
('Jesús María', 5),
('Cosquín', 5),
('La Falda', 5),
('Río Tercero', 5),
('Corrientes', 6),
('Goya', 6),
('Mercedes', 6),
('Paso de los Libres', 6),
('Bella Vista', 6),
('Santo Tomé', 6),
('Esquina', 6),
('Monte Caseros', 6),
('Curuzú Cuatiá', 6),
('Ituzaingó', 6),
('Paraná', 7),
('Concordia', 7),
('Gualeguaychú', 7),
('La Paz', 7),
('Victoria', 7),
('Colón', 7),
('Gualeguay', 7),
('Nogoyá', 7),
('Chajarí', 7),
('Villaguay', 7),
('Formosa', 8),
('Clorinda', 8),
('Pirané', 8),
('El Colorado', 8),
('Ingeniero Juárez', 8),
('Laguna Blanca', 8),
('Ibarreta', 8),
('Las Lomitas', 8),
('Villa Dos Trece', 8),
('General Belgrano', 8),
('San Salvador de Jujuy', 9),
('Palpalá', 9),
('Libertador San Martín', 9),
('La Quiaca', 9),
('Perico', 9),
('El Carmen', 9),
('Tilcara', 9),
('Humahuaca', 9),
('San Pedro', 9),
('Abra Pampa', 9),
('Santa Rosa', 10),
('General Pico', 10),
('Toay', 10),
('Realicó', 10),
('25 de Mayo', 10),
('General Acha', 10),
('Victorica', 10),
('Intendente Alvear', 10),
('Macachín', 10),
('Eduardo Castex', 10),
('La Rioja', 11),
('Chilecito', 11),
('Aimogasta', 11),
('Chamical', 11),
('Chepes', 11),
('Famatina', 11),
('Villa Unión', 11),
('Castro Barros', 11),
('Olta', 11),
('Sanagasta', 11),
('Mendoza', 12),
('San Rafael', 12),
('Godoy Cruz', 12),
('Malargüe', 12),
('Maipú', 12),
('Luján de Cuyo', 12),
('Las Heras', 12),
('Tunuyán', 12),
('General Alvear', 12),
('San Martín', 12),
('Posadas', 13),
('Eldorado', 13),
('Oberá', 13),
('Puerto Iguazú', 13),
('Apóstoles', 13),
('San Vicente', 13),
('Montecarlo', 13),
('Jardín América', 13),
('Leandro N. Alem', 13),
('Aristóbulo del Valle', 13),
('Neuquén', 14),
('Cutral Co', 14),
('Plottier', 14),
('Zapala', 14),
('Centenario', 14),
('San Martín de los Andes', 14),
('Chos Malal', 14),
('Rincón de los Sauces', 14),
('Villa La Angostura', 14),
('Senillosa', 14),
('Viedma', 15),
('Bariloche', 15),
('General Roca', 15),
('Cipolletti', 15),
('Villa Regina', 15),
('Catriel', 15),
('Choele Choel', 15),
('Allen', 15),
('El Bolsón', 15),
('San Antonio Oeste', 15),
('Salta', 16),
('Orán', 16),
('Tartagal', 16),
('Metán', 16),
('Rosario de la Frontera', 16),
('Cafayate', 16),
('General Güemes', 16),
('Joaquín V. González', 16),
('Embarcación', 16),
('Aguaray', 16),
('San Juan', 17),
('Rawson', 17),
('Chimbas', 17),
('Pocito', 17),
('Rivadavia', 17),
('Santa Lucía', 17),
('Caucete', 17),
('Albardón', 17),
('San Martín', 17),
('Jáchal', 17),
('San Luis', 18),
('Villa Mercedes', 18),
('La Punta', 18),
('Merlo', 18),
('Justo Daract', 18),
('Concarán', 18),
('Villa de Merlo', 18),
('Tilisarao', 18),
('Buena Esperanza', 18),
('Luján', 18),
('Río Gallegos', 19),
('Caleta Olivia', 19),
('El Calafate', 19),
('Puerto Deseado', 19),
('Pico Truncado', 19),
('Las Heras', 19),
('Perito Moreno', 19),
('Gobernador Gregores', 19),
('San Julián', 19),
('28 de Noviembre', 19),
('Santa Fe', 20),
('Rosario', 20),
('Rafaela', 20),
('Venado Tuerto', 20),
('Reconquista', 20),
('Villa Constitución', 20),
('Esperanza', 20),
('San Lorenzo', 20),
('Casilda', 20),
('Cañada de Gómez', 20),
('Santiago del Estero', 21),
('La Banda', 21),
('Añatuya', 21),
('Frías', 21),
('Fernández', 21),
('Loreto', 21),
('Monte Quemado', 21),
('Quimilí', 21),
('Clodomira', 21),
('Suncho Corral', 21),
('Ushuaia', 22),
('Río Grande', 22),
('Tolhuin', 22),
('Puerto Almanza', 22),
('San Sebastián', 22),
('Lago Escondido', 22),
('Bahía Thetis', 22),
('Bahía Buen Suceso', 22),
('Puerto Parry', 22),
('Puerto Ranquel', 22),
('San Miguel de Tucumán', 23),
('Yerba Buena', 23),
('Tafí Viejo', 23),
('Concepción', 23),
('Aguilares', 23),
('Monteros', 23),
('Banda del Río Salí', 23),
('Lules', 23),
('Famaillá', 23),
('Bella Vista', 23),
('Buenos Aires', 24),
('Recoleta', 24),
('Palermo', 24),
('Belgrano', 24),
('Caballito', 24),
('Flores', 24),
('Retiro', 24),
('San Telmo', 24),
('Villa Urquiza', 24),
('Villa Devoto', 24);

INSERT INTO tipo_movimiento (descripcion) VALUES
('Alta de cuenta'),
('Alta de préstamo'),
('Pago de préstamo'),
('Transferencia');

INSERT INTO estado_prestamo (descripcion) VALUES
('Pendiente'),
('Aprobado'),
('Rechazado');

-- Precarga de clientes (integrantes del grupo)

INSERT INTO clientes (dni, cuil, nombre, apellido, sexo, id_nacionalidad, fecha_nacimiento, direccion, id_localidad, id_provincia, correo_electronico, telefono, activo)
VALUES

('30011111', '20-30011111-3', 'Mauro', 'Asselborn', 'Masculino', 1, '1992-07-27', 'Calle Alsina 272', 9, 9, 'mauro.asselborn@gmail.com', '1144965827', 1),
('30022222', '20-30022222-3', 'Adriel', 'Logullo', 'Masculino', 3, '1991-08-26', 'Calle Belgrano 218', 8, 8, 'adriel.logullo@gmail.com', '1148868537', 1),
('30033333', '20-30033333-3', 'Franco', 'Bonzi', 'Masculino', 2, '1994-08-16', 'Pasaje San Martín 845', 19, 19, 'franco.bonzi@gmail.com', '1141505620', 1),
('30044444', '20-30044444-3', 'Guido', 'Secovih', 'Masculino', 5, '1987-02-14', 'Calle Alsina 119', 7, 7, 'guido.secovih@gmail.com', '1140248697', 1),
('30055555', '20-30055555-3', 'Adrian', 'Criscione', 'Masculino', 8, '1997-03-20', 'Pasaje Alsina 279', 20, 20, 'adrian.criscione@gmail.com', '1142991320', 1),
('30066666', '20-30066666-3', 'Mariano', 'Stoesell', 'Masculino', 6, '1985-01-13', 'Pasaje Belgrano 331', 10, 10, 'mariano.stoesell@gmail.com', '1141350433', 1);

-- Precarga de usuarios

INSERT INTO usuarios (id_cliente, id_tipo_usuario, nombre_usuario, contrasena, activo)
VALUES

(1, 2, 'mauro', '1234', 1),
(2, 1, 'adriel', '1234', 1),
(3, 1, 'franco', '1234', 1),
(4, 1, 'guido', '1234', 1),
(5, 2, 'adrian', '1234', 1),
(6, 2, 'mariano', '1234', 1);


-- Precarga de Tipos de Cuentas
INSERT INTO tipo_cuenta (descripcion) VALUES
('Caja de ahorro'),
('Cuenta corriente');
